
name: Spring Boot Gradle Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v3

      - name: Step 2 - Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Step 3 - Build project
        run: |
          cd demo
          chmod +x gradlew
          ./gradlew build

          
      - name: Build Docker Image
        run: docker build -t springboot-app .


      - name: Step 4 - Run tests
        run: |
          cd demo
          ./gradlew test

      - name: Step 5 - Start application
        run: |
          cd demo
          nohup ./gradlew bootRun &
          sleep 20

      - name: Step 6 - Verify application
        run: |
          curl http://localhost:8080/hello
