
name: DevOps Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Check code
        uses: actions/checkout@v3

      - name: Step 2 - Run simple command
        run: echo "My first DevOps pipeline is running!"
